version: '3'

services:

  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.env.example:.env -wait tcp://db:3306 -timeout 25s npm run dev
    volumes:
      - .:/usr/src/app
      - /node_modules
    networks:
      - nodenet
    depends_on:
      - db

  db:
    build:
      context: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fcdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    networks:
      - nodenet

  webserver:
    build:
      context: .docker/nginx
    container_name: webserver
    networks:
      - nodenet
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  nodenet: